packages:
  - "."

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - axi-sdk-js
  - "@runecraft/sq-gh"
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
