#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by sq-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/sq-brief.sh"
TMP_ROOT=$(fm_test_tmproot sq-ask-user-authority)

test_primary_and_XO_instruction_generation() {
  local home ship charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  SQUAD_HOME="$home" SQUAD_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$ship" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "Squad applies the authority contract in its \`AGENTS.md\`" "$ship" \
    "generated implementation brief bypasses the primary authority owner"
  assert_grep "silently bypass Squad's authority check and any required commander escalation" "$ship" \
    "generated implementation brief permits silent ask-user auto-resolution"
  assert_no_grep 'the commander, not you, owns the ask-user decisions' "$ship" \
    "generated implementation brief retained conflicting commander-only wording"

  SQUAD_HOME="$home" SQUAD_ROOT_OVERRIDE="$ROOT" SQUAD_XO_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --xo --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated XO charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated XO charter duplicated the detailed authority procedure"
  pass "primary workers and XOs receive the authority rule through generated instructions"
}

test_primary_and_XO_instruction_generation
