#!/usr/bin/env bash
set -eu
set -o pipefail

base_sha="${1:?base sha required}"
head_sha="${2:?head sha required}"

violated=$(
  git diff --name-status --find-renames --find-copies --find-copies-harder "${base_sha}...${head_sha}" |
    awk '
      function generated(path) {
        return path == "CHANGELOG.md" || path == ".release-please-manifest.json"
      }
      $1 == "A" && $2 == ".release-please-manifest.json" { next }
      $1 == "A" && generated($2) {
        printf " %s", $2
      }
      $1 ~ /^[MDT]/ && generated($2) {
        printf " %s", $2
      }
      $1 ~ /^[RC]/ && (generated($2) || generated($3)) {
        if (NF >= 3) {
          printf " %s -> %s", $2, $3
        } else {
          printf " %s", $2
        }
      }
    '
)

if [ -n "$violated" ]; then
  {
    echo "::error::This PR modifies release-please-generated files:${violated}"
    echo
    echo "CHANGELOG.md and .release-please-manifest.json are auto-generated by"
    echo "release-please from conventional commits on main. Do not hand-edit them."
    echo
    echo "If you want your change to appear in the next release notes, use a"
    echo "conventional commit message (feat/fix/docs/...). release-please will"
    echo "update these files in the next release PR automatically."
    echo
    echo "See CONTRIBUTING.md for the full contributor workflow."
  } >&2
  exit 1
fi

echo "No release-please-generated files modified. OK."
